# Generated by Django 5.0.6 on 2024-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_brand_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quatity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
