# Generated by Django 5.0.6 on 2024-06-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_quatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
