# Generated by Django 5.0.6 on 2024-06-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='car',
        ),
    ]
